Create package.json
flo-f/DualListBox pull request #1
Opened 2019-06-10 17:02 UTC by ilyazub

2019-06-10 22:32 UTC, hheimbuerger commented on package.json
> +    "hheimbuerger"
Add @flo-f (ahead of myself) please.

2019-06-11 07:50 UTC, ilyazub commented on package.json
> +    "hheimbuerger"
Done.

2019-06-11 07:56 UTC, ilyazub commented
Just checked. Page that uses `dual-list-box` works fine.

2019-06-11 10:09 UTC, hheimbuerger requested changes
Please fix the license as noted on another (non-review) comment.

2019-06-11 10:09 UTC, hheimbuerger commented on package.json
> +  "license": "ISC",
The source of our fork appears to be MIT, so let's stick to that.

2019-06-11 12:58 UTC, ilyazub commented on package.json
> +  "license": "ISC",
Done.

2019-06-11 13:00 UTC, hheimbuerger approved these changes

2019-06-11 13:01 UTC, merged